version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Tbilisi
    groups:
      github-actions-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Tbilisi
    groups:
      root-composer-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: composer
    directory: /tools/qa
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Tbilisi
    groups:
      qa-composer-minor-patch:
        update-types:
          - minor
          - patch
