sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.php.coverage.reportPaths=build/coverage/clover.xml
sonar.php.psalm.reportPaths=build/reports/psalm.sonarqube.json
sonar.qualitygate.wait=true
sonar.exclusions=vendor/**,build/**,data/**
sonar.test.exclusions=vendor/**,build/**
